### ISSUE TITLE
wk07-hw data

### ISSUE THREAD

**Issue by nicoleloeb** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#10]
Hello! 

Is the phosphorus dataset we are using the same as what is used in the example plot? My figure for the chlorophyll data looks the same as in the plot in the readme (other than formatting, of course), but the phosphorus one is different (I have more observations than the example). I just wanted to double-check if the data is supposed to be the same!

Thanks!!

**Comment by peperg** [comment]
@nicoleloeb, thank you very much for your mesage. I actually just found a small error in the isntructions of the assignment. My original text had a section indicating that the plots showed the data for the **surface** of the lake (i.e. depth = 0 m), but it seems that that section did not make it to the README. Very sorry about that.

Feel free to add the small filtration step (no more than one line of code for each dataset) and run it all again and update your repo if you'd like. That being said, because this was on me, if you already did it without filtering, i will not consider it wrong.

Good catch and sorry!

Pepe
