### ISSUE TITLE
Error message: Invalid input: time_trans works with objects of class POSIXct only

### ISSUE THREAD

**Issue by fowziaahmed** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#18]
Hello everyone,

Yes, definitely dates are complicated. I am getting this error message while creating the plot for wk 08 homework. I tried `mutate(year = as.factor(year)`, `mutate(sampling_date = ymd(sampling_date)`. I also tried to use `as.PROSIXct`, but it can not read the value from the table. What should I do?

I used  `scale_x_datetime(date_breaks = "2 years", date_labels = "%Y")` this code with ggplot. Is this ok?

Could anyone help?

**Comment by YananR** [comment]
Hello, 

You don't need to put yy, mm, dd together. Just to join and bind data (nutrients, basin) to the new table (this one is used for plotting) with year value. The new data set `%>% mutate(year = as.factor(year)`. You don't need to change the x scale, since plotting `geom_boxplot(aes(x = year, y = concentration)` will only show 2002 and 2004.

**Comment by fowziaahmed** [comment]
Thanks @YananR for your reply. I removed NA and scale_x_datetime. Now it works.
Thanks a lot.

**Comment by peperg** [comment]
Hello @fowziaahmed and @YananR ,

@YananR is correct, in this case it is not necesary to turn the years into dates. We only need to let R know that a certain object is a date or a timestamp if we are going to need them as such for an analysis or plot. For example, if we have a bunch of dates and want to plot a time series, we nee dto make these a date object so R knows how to properly space them and order them, otherwise R just sees them as text and will treat them as a factor. As such they would be equally space and the order would be alphabetical, which might not match the order of the actual dates or the spacing (imagine you are missing days, the spacing would still be euqal betwene all factors.

In this case, we dont really need R to think of these objects as dates. We actually kind of prefere them to be treated them as factors, as we are just comparing a group of samples (2002) vs another (2004). The temporal relationship between them here is not that relevant. As such, it is easier to just make sure that variable is propoerly used as a factor by explicitly making it so, and we save all the complication of making it a date.

I hope that makes sense!

Pepe

**Comment by fowziaahmed** [comment]
Thanks a lot @peperg . Yes, that makes sense.
