### ISSUE TITLE
committing changes

### ISSUE THREAD

**Issue by maddperr** [UM-R-for-EnvSci-Registered-Student-2021/General_Discussion#6]
I have finished week 5 assignment, but once again when I go to commit changes it says that there are no changes to commit. I can see my work in the environment. however, when I click on the Git tab there is nothing here. I've tried restarting and still nothing. Not sure why this keeps happening.

**Comment by jkozak180** [comment]
Hey, I often have this problem too. I'm not sure what is the actual 'right' way to fix this, but there are a few things I've done to 'fix' it and eventually get it back to GitHub;
* Changing/putting a comment and committing that new comment first from the Git tab > commentaries > commentary box
* Keep spamming the push buttons from the Git environment tab, or checking off 'Staged' box then pushing from the Review Changes window
* If I don't complete everything in one sitting I have to redownload the repo, paste the changes (backspace and reenter the first letter of each code chunk) and then push everything back. Its tedious, but this one seems to work the best for me. 

Most times it just feels like luck that the changes actually appear on GitHub even after all the changes were supposedly pushed back, and 'all changes are up to date' despite not showing up. I'd love to hear how everyone else is battling this issue though, if they are experiencing it.

**Comment by peperg** [comment]
Hello @maddperr and @jkozak180, Just wanted to check how you are doing with this issue.

@jkozak180, thank you for the input. Your options are good, but we should take a look at to why this is hapening, it shouldnt be needed to go throuugh all that trouble.

Of course, i know thi sis probably not the case, but just checking all options. Have you made sure that:

a) You are working in an `r script` file (`.R`) (as oposit to writing the code in the terminal) and 
b) you are **saving** the file before trying to comit (i know this sounds silly, but i have done this a bunch of times... get confused as to why the changes are not showing in the commit window, to then realize that... there are no changes to commit because i didnt save the file)

Lets see if we can figure out what is happening.
